# Generated by Django 4.2.3 on 2024-01-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=500)),
                ('District', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=500)),
                ('Dproof', models.ImageField(upload_to='dproof_DB')),
                ('Mincharge', models.IntegerField()),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
