# Generated by Django 4.2.3 on 2023-08-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ration_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=20)),
                ('Village', models.CharField(max_length=50)),
                ('Ward', models.IntegerField()),
                ('Contact', models.IntegerField()),
                ('Aadhar', models.IntegerField()),
                ('Location', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='product_DB')),
                ('Landmark', models.IntegerField()),
                ('Working', models.CharField(max_length=15)),
                ('coordinator', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
