# Generated by Django 4.2.3 on 2023-08-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rationshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ration_db',
            name='Landmark',
            field=models.CharField(max_length=50),
        ),
    ]
