# Generated by Django 4.2.3 on 2023-10-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rationshop', '0002_alter_ration_db_landmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.CharField(max_length=20)),
                ('Quantity', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=20)),
                ('Cardtype', models.CharField(max_length=50)),
                ('Ration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rationshop.ration_db')),
            ],
        ),
    ]
