# Generated by Django 4.2.3 on 2023-10-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rationshop', '0003_items_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration_db',
            name='shopImage',
            field=models.ImageField(default=True, upload_to='shop_img'),
        ),
    ]
