# Generated by Django 4.2.6 on 2023-11-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rationshop', '0005_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
